"""initial migration

Revision ID: 968188240638
Revises: 
Create Date: 2018-08-22 13:15:42.748622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '968188240638'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emp')
    op.drop_table('EMP')
    op.drop_table('student')
    op.drop_table('works')
    op.drop_table('dept')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dept',
    sa.Column('did', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('dname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('budget', mysql.FLOAT(), nullable=True),
    sa.Column('managerid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('did'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('works',
    sa.Column('eid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('did', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pcttime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('eid', 'did'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('EMP',
    sa.Column('eid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ename', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('salary', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('eid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('emp',
    sa.Column('eid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ename', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('salary', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('eid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
